"""Protocol schema constants."""

from __future__ import annotations

TASK_CONTRACT = "faber.task_contract.v1"
ATTEMPT = "faber.attempt.v1"
VERIFIER_RUN = "faber.verifier_run.v1"
VERIFICATION_RECEIPT = "faber.verification_receipt.v1"
TRAJECTORY = "faber.trajectory.v1"
SETTLEMENT = "faber.settlement.v1"
WORKER_PROFILE = "faber.worker_profile.v1"
ROUTER_DECISION = "faber.router_decision.v1"
MARKET_EVENT = "faber.market_event.v1"
EVIDENCE_LEVEL = "faber.evidence_level.v1"
TRACE_EVENT = "faber.trace_event.v1"
TRACE_MANIFEST = "faber.trace_manifest.v1"
ATTEMPT_MANIFEST = "faber.attempt_manifest.v1"
REDACTION_POLICY = "faber.redaction_policy.v1"
ATTESTATION = "faber.attestation.v1"
EPISODE_PACKAGE = "faber.episode_package.v1"
MODEL_MANIFEST = "faber.model_manifest.v1"
HARNESS_MANIFEST = "faber.harness_manifest.v1"
ENVIRONMENT_MANIFEST = "faber.environment_manifest.v1"
